# Generated by Django 4.2 on 2024-09-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
